/// Decides whether OPTIONAL cloud features are available. Cloud is OFF unless
/// the app was compiled with `--dart-define=TARF_CLOUD=true` AND Firebase
/// config is present (firebase_options.dart generated by the owner). Guest
/// mode is the default and never depends on this being true.
class FirebaseFlags {
  const FirebaseFlags({
    required this.configPresent,
    this.compileEnabled = const bool.fromEnvironment('TARF_CLOUD'),
  });

  /// Whether `Firebase.initializeApp` succeeded with real options.
  final bool configPresent;

  /// Compile-time master switch.
  final bool compileEnabled;

  bool get cloudEnabled => compileEnabled && configPresent;

  /// Sign-in UI is only enabled when cloud is fully available.
  bool get signInAvailable => cloudEnabled;
}
